### ISSUE TITLE
to() Type Transformation

### ISSUE THREAD

**Issue by deepaknc** [reddragon/eclisp#2]
You might want to move this out to another class as well. Ideally, the Value class should have very specific functionality - all transformation, creating new objects etc could possibly move out. Not sure how the strategy pattern can be implemented in golang, but seems like a good opportunity to use it :-)

https://github.com/reddragon/eclisp/blob/master/lang/value.go#L24

**Comment by reddragon** [comment]
Good point. I was thinking of doing it that way too. 

But, I designed it this way to be able to add new Value types which were completely independent, and self-contained. Any struct which implements the Value interface is pretty much set to be used. Otherwise, I'll need to make changes in multiple places (ValueFactory, ConvertType method, etc.).

Mostly modeled on Rob Pike's ivy talk: https://www.youtube.com/watch?v=PXoG0WX0r_E
